PythonDjango Sample
microsoftgraph/msgraph-training-pythondjangoapp pull request #111
Opened 2022-08-17 21:33 UTC by dodaromike

2022-08-22 18:39 UTC, jasonjoh requested changes
Good start, but it looks like this is a work in progress? The project isn't complete.

2022-08-22 18:39 UTC, jasonjoh commented on README.md
> +# Build Python Django apps with Microsoft Graph
Update the title: Microsoft Graph sample Python web app

2022-08-22 18:39 UTC, jasonjoh commented on README.md
> +- [Python Microsoft Graph tutorial](https://docs.microsoft.com/graph/tutorials/python)
Remove this line

2022-08-22 18:39 UTC, jasonjoh commented on README.md
> +    ![A screenshot of the App registrations ](/tutorial/images/aad-portal-app-registrations.png)
Remove all of the screenshots from this section.

2022-08-23 11:51 UTC, dodaromike commented
Copied the project files to branch for review. Ready for review.

2022-08-24 20:57 UTC, jasonjoh approved these changes

2022-08-25 12:43 UTC, merged